name: Abstract Plugin

on:
  workflow_call:
    inputs:
      version:
        description: 'Build version'
        required: true
        type: string
        default: '3.0.0'
      is-release:
        description: 'Release'
        type: boolean
        default: false
      plugin-folder:
        description: 'Plugin source files folder'
        type: string
        required: true
      files-to-sign:
        description: 'Files to sign (comma-separated list)'
        type: string
        required: true
      plugin-friendly-name:
        description: 'Plugin friendly name'
        type: string
        required: true
      github-tag-prefix:
        description: 'GitHub tag prefix'
        type: string
        required: true


jobs:

  build:

    name: Build ${{ inputs.version }}
    runs-on: windows-latest
    env:
      Scripts: .\.github\workflows\scripts
      TemporaryPfxFilePath: .\GitHubActionsWorkflow.pfx
      PublishOutputPath: .\${{ inputs.plugin-folder }}\bin\Release\net7.0-windows\publish
      DistributionZipFilePath: .\${{ inputs.github-tag-prefix }}.zip

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: |
        dotnet publish ./${{ inputs.plugin-folder }}/${{ inputs.plugin-folder }}.csproj `
          -c Release `
          -o ${{ env.PublishOutputPath }} `
          --nologo `
          /p:Version=${{ inputs.version }}

    - name: Sign code files
      run: |
        ${{ env.Scripts }}\DecodePfx.ps1 `
          -Base64Pfx "${{ secrets.BASE64_ENCODED_PFX }}" `
          -OutputPath ${{ env.TemporaryPfxFilePath }}
        ${{ env.Scripts }}\SignMyCodeFiles.ps1 `
          -FilesDirectoryPath ${{ env.PublishOutputPath }} `
          -PfxFilePath ${{ env.TemporaryPfxFilePath }} `
          -PfxPassword ${{ secrets.PFX_KEY }} `
          -FileNamesToInclude ${{ inputs.files-to-sign }}
        Remove-Item -Path ${{ env.TemporaryPfxFilePath }}

    - name: Zip
      run: Compress-Archive -Path ${{ env.PublishOutputPath }}\* -DestinationPath ${{ env.DistributionZipFilePath }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: Output
        path: |
          ${{ env.DistributionZipFilePath }}
          .\${{ inputs.plugin-folder }}\ReleaseNotes.md


  github-release:

    name: Release ${{ inputs.version }}
    if: github.event_name != 'pull_request' && inputs.is-release
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4

    - name: GitHub release
      env:
        GH_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create '${{ inputs.github-tag-prefix }}-${{ inputs.version }}' (Get-Item Output/*.zip) `
          --draft `
          --title '${{ inputs.plugin-friendly-name }} ${{ inputs.version }}' `
          --notes-file 'Output/${{ inputs.plugin-folder }}/ReleaseNotes.md'
      # uses: softprops/action-gh-release@v0.1.15
      # with:
      #   name: '${{ inputs.plugin-friendly-name }} ${{ inputs.version }}'
      #   tag_name: '${{ inputs.github-tag-prefix }}-${{ inputs.version }}'
      #   draft: true
      #   files: '**/*.zip'
      #   body_path: 'Output/${{ inputs.plugin-folder }}/ReleaseNotes.md'
      #   fail_on_unmatched_files: true
