name: Images Plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Build version'
        required: true
        type: string
        default: '2.0.0'
      is-release:
        description: 'Release'
        type: boolean
        default: false
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Tum4ik.JustClipboardManager.ImagesPlugin/**'


jobs:

  call-plugin-workflow:
    name: Images Plugin
    uses: ./.github/workflows/abstract-plugin.yml
    with:
      version: ${{ inputs.version }}
      is-release: ${{ inputs.is-release }}
      plugin-folder: 'Tum4ik.JustClipboardManager.ImagesPlugin'
      files-to-sign: 'Tum4ik.JustClipboardManager.ImagesPlugin.dll'
      plugin-friendly-name: 'Images Plugin'
      github-tag-prefix: 'images-plugin'
    secrets: inherit
    permissions:
      contents: write
